var namespaceafio__v2__xxx =
[
    [ "algorithm", "namespaceafio__v2__xxx_1_1algorithm.html", "namespaceafio__v2__xxx_1_1algorithm" ],
    [ "path_discovery", "namespaceafio__v2__xxx_1_1path__discovery.html", "namespaceafio__v2__xxx_1_1path__discovery" ],
    [ "storage_profile", "namespaceafio__v2__xxx_1_1storage__profile.html", "namespaceafio__v2__xxx_1_1storage__profile" ],
    [ "utils", "namespaceafio__v2__xxx_1_1utils.html", "namespaceafio__v2__xxx_1_1utils" ],
    [ "async_file_handle", "classafio__v2__xxx_1_1async__file__handle.html", "classafio__v2__xxx_1_1async__file__handle" ],
    [ "construct", "structafio__v2__xxx_1_1construct.html", "structafio__v2__xxx_1_1construct" ],
    [ "construct< algorithm::cached_parent_handle_adapter< T > >", "structafio__v2__xxx_1_1construct_3_01algorithm_1_1cached__parent__handle__adapter_3_01_t_01_4_01_4.html", "structafio__v2__xxx_1_1construct_3_01algorithm_1_1cached__parent__handle__adapter_3_01_t_01_4_01_4" ],
    [ "construct< async_file_handle >", "structafio__v2__xxx_1_1construct_3_01async__file__handle_01_4.html", "structafio__v2__xxx_1_1construct_3_01async__file__handle_01_4" ],
    [ "construct< directory_handle >", "structafio__v2__xxx_1_1construct_3_01directory__handle_01_4.html", "structafio__v2__xxx_1_1construct_3_01directory__handle_01_4" ],
    [ "construct< file_handle >", "structafio__v2__xxx_1_1construct_3_01file__handle_01_4.html", "structafio__v2__xxx_1_1construct_3_01file__handle_01_4" ],
    [ "construct< map_handle >", "structafio__v2__xxx_1_1construct_3_01map__handle_01_4.html", "structafio__v2__xxx_1_1construct_3_01map__handle_01_4" ],
    [ "construct< mapped_file_handle >", "structafio__v2__xxx_1_1construct_3_01mapped__file__handle_01_4.html", "structafio__v2__xxx_1_1construct_3_01mapped__file__handle_01_4" ],
    [ "construct< path_handle >", "structafio__v2__xxx_1_1construct_3_01path__handle_01_4.html", "structafio__v2__xxx_1_1construct_3_01path__handle_01_4" ],
    [ "construct< section_handle >", "structafio__v2__xxx_1_1construct_3_01section__handle_01_4.html", "structafio__v2__xxx_1_1construct_3_01section__handle_01_4" ],
    [ "deadline", "structafio__v2__xxx_1_1deadline.html", "structafio__v2__xxx_1_1deadline" ],
    [ "directory_entry", "structafio__v2__xxx_1_1directory__entry.html", "structafio__v2__xxx_1_1directory__entry" ],
    [ "directory_handle", "classafio__v2__xxx_1_1directory__handle.html", "classafio__v2__xxx_1_1directory__handle" ],
    [ "error_code", "structafio__v2__xxx_1_1error__code.html", "structafio__v2__xxx_1_1error__code" ],
    [ "file_handle", "classafio__v2__xxx_1_1file__handle.html", "classafio__v2__xxx_1_1file__handle" ],
    [ "fs_handle", "classafio__v2__xxx_1_1fs__handle.html", "classafio__v2__xxx_1_1fs__handle" ],
    [ "handle", "classafio__v2__xxx_1_1handle.html", "classafio__v2__xxx_1_1handle" ],
    [ "io_handle", "classafio__v2__xxx_1_1io__handle.html", "classafio__v2__xxx_1_1io__handle" ],
    [ "io_service", "classafio__v2__xxx_1_1io__service.html", "classafio__v2__xxx_1_1io__service" ],
    [ "log_level_guard", "classafio__v2__xxx_1_1log__level__guard.html", "classafio__v2__xxx_1_1log__level__guard" ],
    [ "map_handle", "classafio__v2__xxx_1_1map__handle.html", "classafio__v2__xxx_1_1map__handle" ],
    [ "mapped_file_handle", "classafio__v2__xxx_1_1mapped__file__handle.html", "classafio__v2__xxx_1_1mapped__file__handle" ],
    [ "native_handle_type", "structafio__v2__xxx_1_1native__handle__type.html", "structafio__v2__xxx_1_1native__handle__type" ],
    [ "path_handle", "classafio__v2__xxx_1_1path__handle.html", "classafio__v2__xxx_1_1path__handle" ],
    [ "path_hasher", "structafio__v2__xxx_1_1path__hasher.html", "structafio__v2__xxx_1_1path__hasher" ],
    [ "path_view", "classafio__v2__xxx_1_1path__view.html", "classafio__v2__xxx_1_1path__view" ],
    [ "section_handle", "classafio__v2__xxx_1_1section__handle.html", "classafio__v2__xxx_1_1section__handle" ],
    [ "stat_t", "structafio__v2__xxx_1_1stat__t.html", "structafio__v2__xxx_1_1stat__t" ],
    [ "statfs_t", "structafio__v2__xxx_1_1statfs__t.html", "structafio__v2__xxx_1_1statfs__t" ]
];