var namespacellfio__v2__xxx =
[
    [ "algorithm", "namespacellfio__v2__xxx_1_1algorithm.html", "namespacellfio__v2__xxx_1_1algorithm" ],
    [ "ip", "namespacellfio__v2__xxx_1_1ip.html", "namespacellfio__v2__xxx_1_1ip" ],
    [ "path_discovery", "namespacellfio__v2__xxx_1_1path__discovery.html", "namespacellfio__v2__xxx_1_1path__discovery" ],
    [ "storage_profile", "namespacellfio__v2__xxx_1_1storage__profile.html", "namespacellfio__v2__xxx_1_1storage__profile" ],
    [ "utils", "namespacellfio__v2__xxx_1_1utils.html", "namespacellfio__v2__xxx_1_1utils" ],
    [ "awaitable_handle", "classllfio__v2__xxx_1_1awaitable__handle.html", "classllfio__v2__xxx_1_1awaitable__handle" ],
    [ "byte_io_handle", "classllfio__v2__xxx_1_1byte__io__handle.html", "classllfio__v2__xxx_1_1byte__io__handle" ],
    [ "byte_io_multiplexer", "classllfio__v2__xxx_1_1byte__io__multiplexer.html", "classllfio__v2__xxx_1_1byte__io__multiplexer" ],
    [ "byte_socket_handle", "classllfio__v2__xxx_1_1byte__socket__handle.html", "classllfio__v2__xxx_1_1byte__socket__handle" ],
    [ "construct", "structllfio__v2__xxx_1_1construct.html", "structllfio__v2__xxx_1_1construct" ],
    [ "construct< algorithm::cached_parent_handle_adapter< T > >", "structllfio__v2__xxx_1_1construct_3_01algorithm_1_1cached__parent__handle__adapter_3_01_t_01_4_01_4.html", "structllfio__v2__xxx_1_1construct_3_01algorithm_1_1cached__parent__handle__adapter_3_01_t_01_4_01_4" ],
    [ "construct< byte_socket_handle >", "structllfio__v2__xxx_1_1construct_3_01byte__socket__handle_01_4.html", "structllfio__v2__xxx_1_1construct_3_01byte__socket__handle_01_4" ],
    [ "construct< directory_handle >", "structllfio__v2__xxx_1_1construct_3_01directory__handle_01_4.html", "structllfio__v2__xxx_1_1construct_3_01directory__handle_01_4" ],
    [ "construct< fast_random_file_handle >", "structllfio__v2__xxx_1_1construct_3_01fast__random__file__handle_01_4.html", "structllfio__v2__xxx_1_1construct_3_01fast__random__file__handle_01_4" ],
    [ "construct< file_handle >", "structllfio__v2__xxx_1_1construct_3_01file__handle_01_4.html", "structllfio__v2__xxx_1_1construct_3_01file__handle_01_4" ],
    [ "construct< listening_byte_socket_handle >", "structllfio__v2__xxx_1_1construct_3_01listening__byte__socket__handle_01_4.html", "structllfio__v2__xxx_1_1construct_3_01listening__byte__socket__handle_01_4" ],
    [ "construct< map_handle >", "structllfio__v2__xxx_1_1construct_3_01map__handle_01_4.html", "structllfio__v2__xxx_1_1construct_3_01map__handle_01_4" ],
    [ "construct< mapped_file_handle >", "structllfio__v2__xxx_1_1construct_3_01mapped__file__handle_01_4.html", "structllfio__v2__xxx_1_1construct_3_01mapped__file__handle_01_4" ],
    [ "construct< path_handle >", "structllfio__v2__xxx_1_1construct_3_01path__handle_01_4.html", "structllfio__v2__xxx_1_1construct_3_01path__handle_01_4" ],
    [ "construct< pipe_handle >", "structllfio__v2__xxx_1_1construct_3_01pipe__handle_01_4.html", "structllfio__v2__xxx_1_1construct_3_01pipe__handle_01_4" ],
    [ "construct< process_handle >", "structllfio__v2__xxx_1_1construct_3_01process__handle_01_4.html", "structllfio__v2__xxx_1_1construct_3_01process__handle_01_4" ],
    [ "construct< section_handle >", "structllfio__v2__xxx_1_1construct_3_01section__handle_01_4.html", "structllfio__v2__xxx_1_1construct_3_01section__handle_01_4" ],
    [ "construct< symlink_handle >", "structllfio__v2__xxx_1_1construct_3_01symlink__handle_01_4.html", "structllfio__v2__xxx_1_1construct_3_01symlink__handle_01_4" ],
    [ "deadline", "structllfio__v2__xxx_1_1deadline.html", "structllfio__v2__xxx_1_1deadline" ],
    [ "directory_entry", "structllfio__v2__xxx_1_1directory__entry.html", "structllfio__v2__xxx_1_1directory__entry" ],
    [ "directory_handle", "classllfio__v2__xxx_1_1directory__handle.html", "classllfio__v2__xxx_1_1directory__handle" ],
    [ "dynamic_thread_pool_group", "classllfio__v2__xxx_1_1dynamic__thread__pool__group.html", "classllfio__v2__xxx_1_1dynamic__thread__pool__group" ],
    [ "error", "classllfio__v2__xxx_1_1error.html", "classllfio__v2__xxx_1_1error" ],
    [ "error_info", "structllfio__v2__xxx_1_1error__info.html", "structllfio__v2__xxx_1_1error__info" ],
    [ "executor", "classllfio__v2__xxx_1_1executor.html", "classllfio__v2__xxx_1_1executor" ],
    [ "fast_random_file_handle", "classllfio__v2__xxx_1_1fast__random__file__handle.html", "classllfio__v2__xxx_1_1fast__random__file__handle" ],
    [ "file_handle", "classllfio__v2__xxx_1_1file__handle.html", "classllfio__v2__xxx_1_1file__handle" ],
    [ "handle", "classllfio__v2__xxx_1_1handle.html", "classllfio__v2__xxx_1_1handle" ],
    [ "listening_byte_socket_handle", "classllfio__v2__xxx_1_1listening__byte__socket__handle.html", "classllfio__v2__xxx_1_1listening__byte__socket__handle" ],
    [ "listening_socket_handle_buffer_types_injector", "structllfio__v2__xxx_1_1listening__socket__handle__buffer__types__injector.html", "structllfio__v2__xxx_1_1listening__socket__handle__buffer__types__injector" ],
    [ "listening_tls_socket_handle", "classllfio__v2__xxx_1_1listening__tls__socket__handle.html", "classllfio__v2__xxx_1_1listening__tls__socket__handle" ],
    [ "lockable_byte_io_handle", "classllfio__v2__xxx_1_1lockable__byte__io__handle.html", "classllfio__v2__xxx_1_1lockable__byte__io__handle" ],
    [ "log_level_guard", "classllfio__v2__xxx_1_1log__level__guard.html", "classllfio__v2__xxx_1_1log__level__guard" ],
    [ "map_handle", "classllfio__v2__xxx_1_1map__handle.html", "classllfio__v2__xxx_1_1map__handle" ],
    [ "mapped", "classllfio__v2__xxx_1_1mapped.html", "classllfio__v2__xxx_1_1mapped" ],
    [ "mapped_file_handle", "classllfio__v2__xxx_1_1mapped__file__handle.html", "classllfio__v2__xxx_1_1mapped__file__handle" ],
    [ "native_handle_type", "structllfio__v2__xxx_1_1native__handle__type.html", "structllfio__v2__xxx_1_1native__handle__type" ],
    [ "path_handle", "classllfio__v2__xxx_1_1path__handle.html", "classllfio__v2__xxx_1_1path__handle" ],
    [ "path_hasher", "structllfio__v2__xxx_1_1path__hasher.html", "structllfio__v2__xxx_1_1path__hasher" ],
    [ "path_view", "classllfio__v2__xxx_1_1path__view.html", "classllfio__v2__xxx_1_1path__view" ],
    [ "path_view_component", "classllfio__v2__xxx_1_1path__view__component.html", "classllfio__v2__xxx_1_1path__view__component" ],
    [ "pipe_handle", "classllfio__v2__xxx_1_1pipe__handle.html", "classllfio__v2__xxx_1_1pipe__handle" ],
    [ "pollable_handle", "classllfio__v2__xxx_1_1pollable__handle.html", "classllfio__v2__xxx_1_1pollable__handle" ],
    [ "process_handle", "classllfio__v2__xxx_1_1process__handle.html", "classllfio__v2__xxx_1_1process__handle" ],
    [ "read_receiver", "classllfio__v2__xxx_1_1read__receiver.html", "classllfio__v2__xxx_1_1read__receiver" ],
    [ "section_handle", "classllfio__v2__xxx_1_1section__handle.html", "classllfio__v2__xxx_1_1section__handle" ],
    [ "stat_t", "structllfio__v2__xxx_1_1stat__t.html", "structllfio__v2__xxx_1_1stat__t" ],
    [ "statfs_t", "structllfio__v2__xxx_1_1statfs__t.html", "structllfio__v2__xxx_1_1statfs__t" ],
    [ "symlink_handle", "classllfio__v2__xxx_1_1symlink__handle.html", "classllfio__v2__xxx_1_1symlink__handle" ],
    [ "tls_socket_source", "classllfio__v2__xxx_1_1tls__socket__source.html", "classllfio__v2__xxx_1_1tls__socket__source" ],
    [ "tls_socket_source_implementation_information", "structllfio__v2__xxx_1_1tls__socket__source__implementation__information.html", "structllfio__v2__xxx_1_1tls__socket__source__implementation__information" ],
    [ "tls_socket_source_registry", "classllfio__v2__xxx_1_1tls__socket__source__registry.html", null ],
    [ "unique_file_lock", "classllfio__v2__xxx_1_1unique__file__lock.html", "classllfio__v2__xxx_1_1unique__file__lock" ],
    [ "write_receiver", "classllfio__v2__xxx_1_1write__receiver.html", "classllfio__v2__xxx_1_1write__receiver" ]
];