var searchData=
[
  ['io_5fhandle',['io_handle',['../classllfio__v2__xxx_1_1io__handle.html',1,'llfio_v2_xxx']]],
  ['io_5fmultiplexer',['io_multiplexer',['../classllfio__v2__xxx_1_1io__multiplexer.html',1,'llfio_v2_xxx']]],
  ['io_5foperation_5fstate',['io_operation_state',['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__operation__state.html',1,'llfio_v2_xxx::io_multiplexer']]],
  ['io_5foperation_5fstate_5fvisitor',['io_operation_state_visitor',['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__operation__state__visitor.html',1,'llfio_v2_xxx::io_multiplexer']]],
  ['io_5frequest',['io_request',['../structllfio__v2__xxx_1_1directory__handle_1_1io__request.html',1,'llfio_v2_xxx::directory_handle::io_request&lt; class &gt;'],['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__request.html',1,'llfio_v2_xxx::io_multiplexer::io_request&lt; T &gt;'],['../structllfio__v2__xxx_1_1symlink__handle_1_1io__request.html',1,'llfio_v2_xxx::symlink_handle::io_request&lt; T, bool &gt;']]],
  ['io_5frequest_3c_20buffers_5ftype_20_3e',['io_request&lt; buffers_type &gt;',['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__request.html',1,'llfio_v2_xxx::io_multiplexer']]],
  ['io_5frequest_3c_20buffers_5ftype_2c_20_5f_5f_5f_5f_20_3e',['io_request&lt; buffers_type, ____ &gt;',['../structllfio__v2__xxx_1_1symlink__handle_1_1io__request_3_01buffers__type_00_01_________01_4.html',1,'llfio_v2_xxx::symlink_handle']]],
  ['io_5frequest_3c_20const_5fbuffers_5ftype_20_3e',['io_request&lt; const_buffers_type &gt;',['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__request.html',1,'llfio_v2_xxx::io_multiplexer']]],
  ['io_5frequest_3c_20const_5fbuffers_5ftype_2c_20_5f_5f_5f_5f_20_3e',['io_request&lt; const_buffers_type, ____ &gt;',['../structllfio__v2__xxx_1_1symlink__handle_1_1io__request_3_01const__buffers__type_00_01_________01_4.html',1,'llfio_v2_xxx::symlink_handle']]],
  ['io_5fresult',['io_result',['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__result.html',1,'llfio_v2_xxx::io_multiplexer']]],
  ['io_5fresult_3c_20buffers_5ftype_20_3e',['io_result&lt; buffers_type &gt;',['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__result.html',1,'llfio_v2_xxx::io_multiplexer']]],
  ['io_5fresult_3c_20const_5fbuffers_5ftype_20_3e',['io_result&lt; const_buffers_type &gt;',['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__result.html',1,'llfio_v2_xxx::io_multiplexer']]],
  ['is_5fattachable',['is_attachable',['../structkvstore__v1__xxx_1_1traits_1_1is__attachable.html',1,'kvstore_v1_xxx::traits']]],
  ['is_5fdetachable',['is_detachable',['../structkvstore__v1__xxx_1_1traits_1_1is__detachable.html',1,'kvstore_v1_xxx::traits']]],
  ['is_5ftrivially_5fattachable',['is_trivially_attachable',['../structkvstore__v1__xxx_1_1traits_1_1is__trivially__attachable.html',1,'kvstore_v1_xxx::traits']]],
  ['is_5ftrivially_5fdetachable',['is_trivially_detachable',['../structkvstore__v1__xxx_1_1traits_1_1is__trivially__detachable.html',1,'kvstore_v1_xxx::traits']]],
  ['item',['item',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_3c_20float_20_3e',['item&lt; float &gt;',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_3c_20io_5fhandle_3a_3aextent_5ftype_20_3e',['item&lt; io_handle::extent_type &gt;',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_3c_20std_3a_3astring_20_3e',['item&lt; std::string &gt;',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_3c_20unsigned_20_3e',['item&lt; unsigned &gt;',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_3c_20unsigned_20long_20long_20_3e',['item&lt; unsigned long long &gt;',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_5fbase',['item_base',['../structllfio__v2__xxx_1_1storage__profile_1_1item__base.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_5ferased',['item_erased',['../structllfio__v2__xxx_1_1storage__profile_1_1item__erased.html',1,'llfio_v2_xxx::storage_profile']]]
];
