var searchData=
[
  ['implementation_5finformation_5ft_0',['implementation_information_t',['../structllfio__v2__xxx_1_1byte__io__multiplexer_1_1implementation__information__t.html',1,'llfio_v2_xxx::byte_io_multiplexer']]],
  ['io_5faware_5fwork_5fitem_1',['io_aware_work_item',['../classllfio__v2__xxx_1_1dynamic__thread__pool__group_1_1io__aware__work__item.html',1,'llfio_v2_xxx::dynamic_thread_pool_group']]],
  ['io_5foperation_5fstate_2',['io_operation_state',['../structllfio__v2__xxx_1_1byte__io__multiplexer_1_1io__operation__state.html',1,'llfio_v2_xxx::byte_io_multiplexer']]],
  ['io_5foperation_5fstate_5fvisitor_3',['io_operation_state_visitor',['../structllfio__v2__xxx_1_1byte__io__multiplexer_1_1io__operation__state__visitor.html',1,'llfio_v2_xxx::byte_io_multiplexer']]],
  ['io_5frequest_4',['io_request',['../structllfio__v2__xxx_1_1byte__io__multiplexer_1_1io__request.html',1,'llfio_v2_xxx::byte_io_multiplexer::io_request&lt; T &gt;'],['../structllfio__v2__xxx_1_1directory__handle_1_1io__request.html',1,'llfio_v2_xxx::directory_handle::io_request&lt; class &gt;'],['../structllfio__v2__xxx_1_1listening__socket__handle__buffer__types__injector_1_1io__request.html',1,'llfio_v2_xxx::listening_socket_handle_buffer_types_injector&lt; Base, SocketType &gt;::io_request&lt; class &gt;'],['../structllfio__v2__xxx_1_1symlink__handle_1_1io__request.html',1,'llfio_v2_xxx::symlink_handle::io_request&lt; T, bool &gt;']]],
  ['io_5frequest_3c_20buffers_5ftype_20_3e_5',['io_request&lt; buffers_type &gt;',['../structllfio__v2__xxx_1_1byte__io__multiplexer_1_1io__request.html',1,'llfio_v2_xxx::byte_io_multiplexer']]],
  ['io_5frequest_3c_20buffers_5ftype_2c_20_5f_5f_5f_5f_20_3e_6',['io_request&lt; buffers_type, ____ &gt;',['../structllfio__v2__xxx_1_1symlink__handle_1_1io__request_3_01buffers__type_00_01_________01_4.html',1,'llfio_v2_xxx::symlink_handle']]],
  ['io_5frequest_3c_20const_5fbuffers_5ftype_20_3e_7',['io_request&lt; const_buffers_type &gt;',['../structllfio__v2__xxx_1_1byte__io__multiplexer_1_1io__request.html',1,'llfio_v2_xxx::byte_io_multiplexer']]],
  ['io_5frequest_3c_20const_5fbuffers_5ftype_2c_20_5f_5f_5f_5f_20_3e_8',['io_request&lt; const_buffers_type, ____ &gt;',['../structllfio__v2__xxx_1_1symlink__handle_1_1io__request_3_01const__buffers__type_00_01_________01_4.html',1,'llfio_v2_xxx::symlink_handle']]],
  ['io_5fresult_9',['io_result',['../structllfio__v2__xxx_1_1byte__io__multiplexer_1_1io__result.html',1,'llfio_v2_xxx::byte_io_multiplexer']]],
  ['io_5fresult_3c_20buffers_5ftype_20_3e_10',['io_result&lt; buffers_type &gt;',['../structllfio__v2__xxx_1_1byte__io__multiplexer_1_1io__result.html',1,'llfio_v2_xxx::byte_io_multiplexer']]],
  ['io_5fresult_3c_20const_5fbuffers_5ftype_20_3e_11',['io_result&lt; const_buffers_type &gt;',['../structllfio__v2__xxx_1_1byte__io__multiplexer_1_1io__result.html',1,'llfio_v2_xxx::byte_io_multiplexer']]],
  ['is_5fattachable_12',['is_attachable',['../structkvstore__v1__xxx_1_1traits_1_1is__attachable.html',1,'kvstore_v1_xxx::traits']]],
  ['is_5fdetachable_13',['is_detachable',['../structkvstore__v1__xxx_1_1traits_1_1is__detachable.html',1,'kvstore_v1_xxx::traits']]],
  ['is_5ftrivially_5fattachable_14',['is_trivially_attachable',['../structkvstore__v1__xxx_1_1traits_1_1is__trivially__attachable.html',1,'kvstore_v1_xxx::traits']]],
  ['is_5ftrivially_5fdetachable_15',['is_trivially_detachable',['../structkvstore__v1__xxx_1_1traits_1_1is__trivially__detachable.html',1,'kvstore_v1_xxx::traits']]],
  ['item_16',['item',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_3c_20byte_5fio_5fhandle_3a_3aextent_5ftype_20_3e_17',['item&lt; byte_io_handle::extent_type &gt;',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_3c_20float_20_3e_18',['item&lt; float &gt;',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_3c_20std_3a_3astring_20_3e_19',['item&lt; std::string &gt;',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_3c_20unsigned_20_3e_20',['item&lt; unsigned &gt;',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_3c_20unsigned_20long_20long_20_3e_21',['item&lt; unsigned long long &gt;',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_5fbase_22',['item_base',['../structllfio__v2__xxx_1_1storage__profile_1_1item__base.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_5ferased_23',['item_erased',['../structllfio__v2__xxx_1_1storage__profile_1_1item__erased.html',1,'llfio_v2_xxx::storage_profile']]]
];
