var searchData=
[
  ['io_5faware_5fwork_5fitem_800',['io_aware_work_item',['../classllfio__v2__xxx_1_1dynamic__thread__pool__group_1_1io__aware__work__item.html',1,'llfio_v2_xxx::dynamic_thread_pool_group']]],
  ['io_5fhandle_801',['io_handle',['../classllfio__v2__xxx_1_1io__handle.html',1,'llfio_v2_xxx']]],
  ['io_5fhandle_5fawareness_802',['io_handle_awareness',['../structllfio__v2__xxx_1_1dynamic__thread__pool__group_1_1io__aware__work__item_1_1io__handle__awareness.html',1,'llfio_v2_xxx::dynamic_thread_pool_group::io_aware_work_item']]],
  ['io_5fmultiplexer_803',['io_multiplexer',['../classllfio__v2__xxx_1_1io__multiplexer.html',1,'llfio_v2_xxx']]],
  ['io_5foperation_5fstate_804',['io_operation_state',['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__operation__state.html',1,'llfio_v2_xxx::io_multiplexer']]],
  ['io_5foperation_5fstate_5fvisitor_805',['io_operation_state_visitor',['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__operation__state__visitor.html',1,'llfio_v2_xxx::io_multiplexer']]],
  ['io_5frequest_806',['io_request',['../structllfio__v2__xxx_1_1symlink__handle_1_1io__request.html',1,'llfio_v2_xxx::symlink_handle::io_request&lt; T, bool &gt;'],['../structllfio__v2__xxx_1_1directory__handle_1_1io__request.html',1,'llfio_v2_xxx::directory_handle::io_request&lt; class &gt;'],['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__request.html',1,'llfio_v2_xxx::io_multiplexer::io_request&lt; T &gt;']]],
  ['io_5frequest_3c_20buffers_5ftype_20_3e_807',['io_request&lt; buffers_type &gt;',['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__request.html',1,'llfio_v2_xxx::io_multiplexer']]],
  ['io_5frequest_3c_20buffers_5ftype_2c_20_5f_5f_5f_5f_20_3e_808',['io_request&lt; buffers_type, ____ &gt;',['../structllfio__v2__xxx_1_1symlink__handle_1_1io__request_3_01buffers__type_00_01_________01_4.html',1,'llfio_v2_xxx::symlink_handle']]],
  ['io_5frequest_3c_20const_5fbuffers_5ftype_20_3e_809',['io_request&lt; const_buffers_type &gt;',['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__request.html',1,'llfio_v2_xxx::io_multiplexer']]],
  ['io_5frequest_3c_20const_5fbuffers_5ftype_2c_20_5f_5f_5f_5f_20_3e_810',['io_request&lt; const_buffers_type, ____ &gt;',['../structllfio__v2__xxx_1_1symlink__handle_1_1io__request_3_01const__buffers__type_00_01_________01_4.html',1,'llfio_v2_xxx::symlink_handle']]],
  ['io_5fresult_811',['io_result',['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__result.html',1,'llfio_v2_xxx::io_multiplexer']]],
  ['io_5fresult_3c_20buffers_5ftype_20_3e_812',['io_result&lt; buffers_type &gt;',['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__result.html',1,'llfio_v2_xxx::io_multiplexer']]],
  ['io_5fresult_3c_20const_5fbuffers_5ftype_20_3e_813',['io_result&lt; const_buffers_type &gt;',['../structllfio__v2__xxx_1_1io__multiplexer_1_1io__result.html',1,'llfio_v2_xxx::io_multiplexer']]],
  ['is_5fattachable_814',['is_attachable',['../structkvstore__v1__xxx_1_1traits_1_1is__attachable.html',1,'kvstore_v1_xxx::traits']]],
  ['is_5fdetachable_815',['is_detachable',['../structkvstore__v1__xxx_1_1traits_1_1is__detachable.html',1,'kvstore_v1_xxx::traits']]],
  ['is_5ftrivially_5fattachable_816',['is_trivially_attachable',['../structkvstore__v1__xxx_1_1traits_1_1is__trivially__attachable.html',1,'kvstore_v1_xxx::traits']]],
  ['is_5ftrivially_5fdetachable_817',['is_trivially_detachable',['../structkvstore__v1__xxx_1_1traits_1_1is__trivially__detachable.html',1,'kvstore_v1_xxx::traits']]],
  ['item_818',['item',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_3c_20float_20_3e_819',['item&lt; float &gt;',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_3c_20io_5fhandle_3a_3aextent_5ftype_20_3e_820',['item&lt; io_handle::extent_type &gt;',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_3c_20std_3a_3astring_20_3e_821',['item&lt; std::string &gt;',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_3c_20unsigned_20_3e_822',['item&lt; unsigned &gt;',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_3c_20unsigned_20long_20long_20_3e_823',['item&lt; unsigned long long &gt;',['../structllfio__v2__xxx_1_1storage__profile_1_1item.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_5fbase_824',['item_base',['../structllfio__v2__xxx_1_1storage__profile_1_1item__base.html',1,'llfio_v2_xxx::storage_profile']]],
  ['item_5ferased_825',['item_erased',['../structllfio__v2__xxx_1_1storage__profile_1_1item__erased.html',1,'llfio_v2_xxx::storage_profile']]]
];
