var searchData=
[
  ['cache_5fstatistics_0',['cache_statistics',['../structllfio__v2__xxx_1_1map__handle_1_1cache__statistics.html',1,'llfio_v2_xxx::map_handle']]],
  ['cached_5fparent_5fhandle_5fadapter_1',['cached_parent_handle_adapter',['../classllfio__v2__xxx_1_1algorithm_1_1cached__parent__handle__adapter.html',1,'llfio_v2_xxx::algorithm']]],
  ['check_5ffor_5fany_5fcompleted_5fio_5fstatistics_2',['check_for_any_completed_io_statistics',['../structllfio__v2__xxx_1_1byte__io__multiplexer_1_1check__for__any__completed__io__statistics.html',1,'llfio_v2_xxx::byte_io_multiplexer']]],
  ['combining_5fhandle_5fadapter_3',['combining_handle_adapter',['../classllfio__v2__xxx_1_1algorithm_1_1combining__handle__adapter.html',1,'llfio_v2_xxx::algorithm']]],
  ['compare_5fvisitor_4',['compare_visitor',['../structllfio__v2__xxx_1_1algorithm_1_1compare__visitor.html',1,'llfio_v2_xxx::algorithm']]],
  ['comparison_5fsummary_5',['comparison_summary',['../structllfio__v2__xxx_1_1algorithm_1_1comparison__summary.html',1,'llfio_v2_xxx::algorithm']]],
  ['const_5fbuffer_5ftype_6',['const_buffer_type',['../structllfio__v2__xxx_1_1byte__io__multiplexer_1_1const__buffer__type.html',1,'llfio_v2_xxx::byte_io_multiplexer']]],
  ['const_5fbuffers_5ftype_7',['const_buffers_type',['../structllfio__v2__xxx_1_1symlink__handle_1_1const__buffers__type.html',1,'llfio_v2_xxx::symlink_handle']]],
  ['construct_8',['construct',['../structllfio__v2__xxx_1_1construct.html',1,'llfio_v2_xxx']]],
  ['construct_3c_20algorithm_3a_3acached_5fparent_5fhandle_5fadapter_3c_20t_20_3e_20_3e_9',['construct&lt; algorithm::cached_parent_handle_adapter&lt; T &gt; &gt;',['../structllfio__v2__xxx_1_1construct_3_01algorithm_1_1cached__parent__handle__adapter_3_01_t_01_4_01_4.html',1,'llfio_v2_xxx']]],
  ['construct_3c_20byte_5fsocket_5fhandle_20_3e_10',['construct&lt; byte_socket_handle &gt;',['../structllfio__v2__xxx_1_1construct_3_01byte__socket__handle_01_4.html',1,'llfio_v2_xxx']]],
  ['construct_3c_20directory_5fhandle_20_3e_11',['construct&lt; directory_handle &gt;',['../structllfio__v2__xxx_1_1construct_3_01directory__handle_01_4.html',1,'llfio_v2_xxx']]],
  ['construct_3c_20fast_5frandom_5ffile_5fhandle_20_3e_12',['construct&lt; fast_random_file_handle &gt;',['../structllfio__v2__xxx_1_1construct_3_01fast__random__file__handle_01_4.html',1,'llfio_v2_xxx']]],
  ['construct_3c_20file_5fhandle_20_3e_13',['construct&lt; file_handle &gt;',['../structllfio__v2__xxx_1_1construct_3_01file__handle_01_4.html',1,'llfio_v2_xxx']]],
  ['construct_3c_20listening_5fbyte_5fsocket_5fhandle_20_3e_14',['construct&lt; listening_byte_socket_handle &gt;',['../structllfio__v2__xxx_1_1construct_3_01listening__byte__socket__handle_01_4.html',1,'llfio_v2_xxx']]],
  ['construct_3c_20map_5fhandle_20_3e_15',['construct&lt; map_handle &gt;',['../structllfio__v2__xxx_1_1construct_3_01map__handle_01_4.html',1,'llfio_v2_xxx']]],
  ['construct_3c_20mapped_5ffile_5fhandle_20_3e_16',['construct&lt; mapped_file_handle &gt;',['../structllfio__v2__xxx_1_1construct_3_01mapped__file__handle_01_4.html',1,'llfio_v2_xxx']]],
  ['construct_3c_20path_5fhandle_20_3e_17',['construct&lt; path_handle &gt;',['../structllfio__v2__xxx_1_1construct_3_01path__handle_01_4.html',1,'llfio_v2_xxx']]],
  ['construct_3c_20pipe_5fhandle_20_3e_18',['construct&lt; pipe_handle &gt;',['../structllfio__v2__xxx_1_1construct_3_01pipe__handle_01_4.html',1,'llfio_v2_xxx']]],
  ['construct_3c_20process_5fhandle_20_3e_19',['construct&lt; process_handle &gt;',['../structllfio__v2__xxx_1_1construct_3_01process__handle_01_4.html',1,'llfio_v2_xxx']]],
  ['construct_3c_20section_5fhandle_20_3e_20',['construct&lt; section_handle &gt;',['../structllfio__v2__xxx_1_1construct_3_01section__handle_01_4.html',1,'llfio_v2_xxx']]],
  ['construct_3c_20symlink_5fhandle_20_3e_21',['construct&lt; symlink_handle &gt;',['../structllfio__v2__xxx_1_1construct_3_01symlink__handle_01_4.html',1,'llfio_v2_xxx']]],
  ['contents_5ftype_22',['contents_type',['../structllfio__v2__xxx_1_1algorithm_1_1contents__visitor_1_1contents__type.html',1,'llfio_v2_xxx::algorithm::contents_visitor']]],
  ['contents_5fvisitor_23',['contents_visitor',['../structllfio__v2__xxx_1_1algorithm_1_1contents__visitor.html',1,'llfio_v2_xxx::algorithm']]]
];
