//! \file afio/afio.hpp The master *latest version* AFIO include file. All AFIO consuming libraries should include this header only.
#include "version.hpp"

#if defined(_MSC_VER) && !defined(__clang__)
#define AFIO_HEADERS_PATH2 AFIO_VERSION_GLUE(v, AFIO_HEADERS_VERSION, /afio.hpp)
#elif !__PCPP_ALWAYS_FALSE__
#define AFIO_HEADERS_PATH2 AFIO_VERSION_GLUE(v, AFIO_HEADERS_VERSION,)/afio.hpp
#endif

#if 0 // cmake's Makefiles and Ninja generators won't pick up dependent headers without this
#include "v2.0/afio.hpp"
#endif

#define AFIO_HEADERS_PATH4(a) #a
#define AFIO_HEADERS_PATH3(a) AFIO_HEADERS_PATH4(a)
//! \brief The AFIO headers path generated by the preprocessor from the version
#define AFIO_HEADERS_PATH AFIO_HEADERS_PATH3(AFIO_HEADERS_PATH2)
#include AFIO_HEADERS_PATH
#undef AFIO_HEADERS_PATH
#undef AFIO_HEADERS_PATH2
#undef AFIO_HEADERS_PATH3
#undef AFIO_HEADERS_PATH4
