//! \file llfio/llfio.hpp The master *latest version* LLFIO include file. All LLFIO consuming libraries should include this header only.
#include "version.hpp"

#if defined(_MSC_VER) && !defined(__clang__) && (!defined(_MSVC_TRADITIONAL) || _MSVC_TRADITIONAL)
#define LLFIO_HEADERS_PATH2 LLFIO_VERSION_GLUE(v, LLFIO_HEADERS_VERSION, /llfio.hpp)
#elif !__PCPP_ALWAYS_FALSE__
#define LLFIO_HEADERS_PATH2 LLFIO_VERSION_GLUE(v, LLFIO_HEADERS_VERSION,)/llfio.hpp
#endif

#if 0  // cmake's Makefiles and Ninja generators won't pick up dependent headers without this
#include "v2.0/llfio.hpp"
#endif

#define LLFIO_HEADERS_PATH4(a) #a
#define LLFIO_HEADERS_PATH3(a) LLFIO_HEADERS_PATH4(a)
//! \brief The LLFIO headers path generated by the preprocessor from the version
#define LLFIO_HEADERS_PATH LLFIO_HEADERS_PATH3(LLFIO_HEADERS_PATH2)
#include LLFIO_HEADERS_PATH
#undef LLFIO_HEADERS_PATH
#undef LLFIO_HEADERS_PATH2
#undef LLFIO_HEADERS_PATH3
#undef LLFIO_HEADERS_PATH4
