/* handle.hpp
A handle to something
(C) 2015 Niall Douglas http://www.nedprod.com/
File Created: Dec 2015


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "../../../handle.hpp"

#include <fcntl.h>
#include <unistd.h>
#if BOOST_AFIO_USE_POSIX_AIO
#include <aio.h>
#endif

BOOST_AFIO_V2_NAMESPACE_BEGIN

// allocate at process start to ensure later failure to allocate won't cause failure
static fixme_path temporary_files_directory_("/tmp/no_temporary_directories_accessible");
const fixme_path &fixme_temporary_files_directory() noexcept
{
  static struct temporary_files_directory_done_
  {
    temporary_files_directory_done_()
    {
      try
      {
        fixme_path::string_type buffer;
        auto testpath = [&]() {
          size_t len = buffer.size();
          if(buffer[len - 1] == '/')
            buffer.resize(--len);
          buffer.append("/afio_tempfile_probe_file.tmp");
          int h = open(buffer.c_str(), O_WRONLY|O_CREAT, 0666);
          if(-1 != h)
          {
            unlink(buffer.c_str());
            close(h);
            buffer.resize(len);
            temporary_files_directory_ = std::move(buffer);
            return true;
          }
          return false;
        };
        // Note that XDG_RUNTIME_DIR is the systemd runtime directory for the current user
        static const char *variables[] = {"TMPDIR", "TMP", "TEMP", "TEMPDIR", "XDG_RUNTIME_DIR"};
        for(size_t n = 0; n < sizeof(variables) / sizeof(variables[0]); n++)
        {
          const char *env = getenv(variables[n]);
          if(env)
          {
            buffer.assign(env);
            if(testpath())
              return;
          }
        }
        // If everything earlier failed e.g. if our environment block is zeroed,
        // fall back to /tmp and then /var/tmp, the last of which should succeed even if tmpfs is not mounted
        buffer.assign("/tmp");
        if(testpath())
          return;
        buffer.assign("/var/tmp");
        if(testpath())
          return;
        // If even no system tmp directory is available, as a hail mary try $HOME
        static const char *variables2[] = {"HOME"};
        for(size_t n = 0; n < sizeof(variables2) / sizeof(variables2[0]); n++)
        {
          const char *env = getenv(variables2[n]);
          if(env)
          {
            buffer.assign(env);
            if(testpath())
              return;
          }
        }
      }
      catch(...)
      {
      }
    }
  } init;
  return temporary_files_directory_;
}

inline result<int> attribs_from_handle_mode_caching_and_flags(native_handle_type &nativeh, file_handle::mode _mode, file_handle::creation _creation, file_handle::caching _caching, file_handle::flag flags) noexcept
{
  int attribs = 0;
  switch(_mode)
  {
  case mode::unchanged:
    return make_errored_result<file_handle>(stl11::errc::invalid_argument);
  case mode::none:
    break;
  case mode::attr_read:
  case mode::read:
    attribs = O_RDONLY;
    nativeh.behaviour |= native_handle_type::disposition::seekable | native_handle_type::disposition::readable;
    break;
  case mode::attr_write:
  case mode::write:
    attribs = O_RDWR;
    nativeh.behaviour |= native_handle_type::disposition::seekable | native_handle_type::disposition::readable | native_handle_type::disposition::writable;
    break;
  case mode::append:
    attribs = O_APPEND;
    nativeh.behaviour |= native_handle_type::disposition::writable | native_handle_type::disposition::append_only;
    break;
  }
  switch(_creation)
  {
  case creation::open_existing:
    break;
  case creation::only_if_not_exist:
    attribs |= O_CREAT | O_EXCL;
    break;
  case creation::if_needed:
    attribs |= O_CREAT;
    break;
  case creation::truncate:
    attribs |= O_TRUNC;
    break;
  }
  switch(_caching)
  {
  case caching::unchanged:
    return make_errored_result<file_handle>(stl11::errc::invalid_argument);
  case caching::none:
    attribs |= O_SYNC | O_DIRECT;
    nativeh.behaviour |= native_handle_type::disposition::aligned_io;
    break;
  case caching::only_metadata:
    attribs |= O_DIRECT;
    nativeh.behaviour |= native_handle_type::disposition::aligned_io;
    break;
  case caching::reads:
    attribs |= O_SYNC;
    break;
  case caching::reads_and_metadata:
#ifdef O_DSYNC
    attribs |= O_DSYNC;
#else
    attribs |= O_SYNC;
#endif
    break;
  case caching::all:
  case caching::safety_fsyncs:
  case caching::temporary:
    break;
  }
}

result<file_handle> file_handle::file(file_handle::path_type _path, file_handle::mode _mode, file_handle::creation _creation, file_handle::caching _caching, file_handle::flag flags) noexcept
{
  result<file_handle> ret(file_handle(std::move(_path), native_handle_type(), _caching, flags));
  native_handle_type &nativeh = ret.get()._v;
  BOOST_OUTCOME_TRY(attribs, attribs_from_handle_mode_caching_and_flags(nativeh, _mode, _creation, _caching, flags));
  nativeh.behaviour |= native_handle_type::disposition::file;
  const char *path_ = ret.value()._path.c_str();
  nativeh.fd = ::open(path_, attribs, 0x1b0 /*660*/);
  if(-1 == nativeh.fd)
    return make_errored_result<file_handle>(errno, last190(ret.value()._path));
  BOOST_AFIO_LOG_FUNCTION_CALL(nativeh.fd);
  if(_creation == creation::truncate && ret.value().are_safety_fsyncs_issued())
    fsync(nativeh.fd);
  return ret;
}

result<file_handle> file_handle::temp_inode(path_type dirpath, mode _mode, flag flags) noexcept
{
  caching _caching = caching::temporary;
  // No need to rename to random on unlink or check inode before unlink
  flags |= flag::unlink_on_close | flag::disable_safety_unlinks;
  result<file_handle> ret(file_handle(path_type(), native_handle_type(), _caching, flags));
  native_handle_type &nativeh = ret.get()._v;
  // Open file exclusively to prevent collision
  BOOST_OUTCOME_TRY(attribs, attribs_from_handle_mode_caching_and_flags(nativeh, _mode, creation::only_if_not_exist, _caching, flags));
  nativeh.behaviour |= native_handle_type::disposition::file;
#ifdef O_TMPFILE
  // Linux has a special flag just for this use case
  attribs|=O_TMPFILE;
  attribs&=~O_EXCL;  // allow relinking later
  const char *path_ = ret.value()._path.c_str();
  nativeh.fd = ::open(path_, attribs, 0600);
  if(-1 != nativeh.fd)
    return ret;
  // If it failed, assume this kernel or FS doesn't support O_TMPFILE
  attribs&=~O_TMPFILE;
  attribs|=O_EXCL;
#endif
  for(;;)
  {
    try
    {
      ret.value()._path = dirpath / (utils::random_string(32) + ".tmp");
    }
    BOOST_OUTCOME_CATCH_ALL_EXCEPTION_TO_RESULT
    const char *path_ = ret.value()._path.c_str();
    nativeh.fd = ::open(path_, attribs, 0600);  // user read/write perms only
    if(-1 == nativeh.fd)
    {
      int errcode = errno;
      if(EEXIST == errcode)
        continue;
      BOOST_AFIO_LOG_FUNCTION_CALL(0);
      return make_errored_result<file_handle>(errcode, path_));
    }
    BOOST_AFIO_LOG_FUNCTION_CALL(nativeh.fd);
    // Immediately unlink after creation
    if(-1 == ::unlink(path_))
      return make_errored_result<file_handle>(errno, path_);
    return ret;
  }
}

result<file_handle> file_handle::clone() const noexcept
{
  BOOST_AFIO_LOG_FUNCTION_CALL(_v.fd);
  result<file_handle> ret(file_handle(_path, native_handle_type(), _caching, _flags));
  ret.value()._v.behaviour = _v.behaviour;
  ret.value()._v.fd = ::dup(_v.fd);
  if(-1 == ret.value()._v.fd)
    return make_errored_result<file_handle>(errno);
  return ret;
}

result<file_handle::path_type> file_handle::relink(path_type newpath) noexcept
{
  BOOST_AFIO_LOG_FUNCTION_CALL(_v.fd);
  if(newpath.is_relative())
    newpath = _path.parent_path() / newpath;
#ifdef O_TMPFILE
  // If the handle was created with O_TMPFILE, we need a different approach
  if(_path.empty() && _caching&caching::temporary)
  {
    char path[PATH_MAX];
    snprintf(path, PATH_MAX, "/proc/self/fd/%d", _v.fd);
    if(-1 == ::linkat(AT_FDCWD, path, AT_FDCWD, newpath.c_str(), AT_SYMLINK_FOLLOW))
      return make_errored_result<path_type>(errno);
  }
  else
#endif
  {
    // FIXME: As soon as we implement fat paths, make this race free
    if(-1 == ::rename(_path.c_str(), newpath.c_str()))
      return make_errored_result<path_type>(errno);
  }
  _path = std::move(newpath);
  return _path;
}

















result<handle> handle::clone(io_service &service, handle::mode mode, handle::caching caching) const noexcept
{
  result<handle> ret(handle(&service, _path, native_handle_type(), _caching, _flags));
  ret.value()._v.behaviour = _v.behaviour;
  // If current handle is read-only and clone request is to add write powers, we can't use dup()
  if(mode != handle::mode::unchanged && !_v.is_writable() && (mode == handle::mode::write || mode == handle::mode::append))
  {
    // Race free fetch the handle's path and reopen it with the new permissions
    // TODO FIXME
    return make_errored_result<handle>(stl11::errc::function_not_supported);
  }
  else
  {
    if(-1 == (ret.value()._v.fd = ::dup(_v.fd)))
      return make_errored_result<handle>(errno);
    // Only care if cloning and changing append only flag
    if(mode != handle::mode::unchanged && (mode == handle::mode::write || mode == handle::mode::append))
    {
      ret.value()._v.behaviour = _v.behaviour & ~(native_handle_type::disposition::seekable | native_handle_type::disposition::readable | native_handle_type::disposition::writable | native_handle_type::disposition::append_only);
      int attribs = 0;
      if(-1 == (attribs = fcntl(ret.value()._v.fd, F_GETFL)))
        return make_errored_result<handle>(errno);
      switch(mode)
      {
      case handle::mode::unchanged:
        break;
      case handle::mode::none:
      case handle::mode::attr_read:
      case handle::mode::attr_write:
      case handle::mode::read:
        return make_errored_result<handle>(stl11::errc::invalid_argument);
      case handle::mode::write:
        attribs &= ~O_APPEND;
        ret.value()._v.behaviour |= native_handle_type::disposition::seekable | native_handle_type::disposition::readable | native_handle_type::disposition::writable;
        break;
      case handle::mode::append:
        attribs |= O_APPEND;
        ret.value()._v.behaviour |= native_handle_type::disposition::append_only | native_handle_type::disposition::writable;
        break;
      }
      if(-1 == fcntl(ret.value()._v.fd, F_SETFL, attribs))
        return make_errored_result<handle>(errno);
    }
    if(caching != handle::caching::unchanged && caching != _caching)
    {
      // TODO: Allow fiddling with O_DIRECT
      return make_errored_result<handle>(stl11::errc::invalid_argument);
    }
  }
  return ret;
}

handle::~handle()
{
  if(_v)
  {
    if(are_safety_fsyncs_issued())
    {
      fsync(_v.fd);
    }
    ::close(_v.fd);
    _v = native_handle_type();
  }
}

template <class CompletionRoutine, class BuffersType, class IORoutine> result<file_handle::io_state_ptr<CompletionRoutine, BuffersType>> file_handle::_begin_io(file_handle::operation_t operation, file_handle::io_request<BuffersType> reqs, CompletionRoutine &&completion, IORoutine &&ioroutine) noexcept
{
  // Need to keep a set of aiocbs matching the scatter-gather buffers
  struct state_type : public _io_state_type<CompletionRoutine, BuffersType>
  {
#if BOOST_AFIO_USE_POSIX_AIO
    struct aiocb aiocbs[1];
#else
#error todo
#endif
    state_type(handle *_parent, operation_t _operation, CompletionRoutine &&f, size_t _items)
        : _io_state_type<CompletionRoutine, BuffersType>(_parent, _operation, std::forward<CompletionRoutine>(f), _items)
    {
    }
    virtual void operator()(long errcode, long bytes_transferred, void *internal_state) noexcept override final
    {
#if BOOST_AFIO_USE_POSIX_AIO
      struct aiocb **_paiocb = (struct aiocb **) internal_state;
      struct aiocb *aiocb = *_paiocb;
      assert(aiocb >= aiocbs && aiocb < aiocbs + this->items);
      *_paiocb = nullptr;
#else
#error todo
#endif
      if(this->result)
      {
        if(errcode)
          this->result = make_errored_result<BuffersType>((int) errcode);
        else
        {
// Figure out which i/o I am and update the buffer in question
#if BOOST_AFIO_USE_POSIX_AIO
          size_t idx = aiocb - aiocbs;
#else
#error todo
#endif
          if(idx >= this->items)
          {
            BOOST_AFIO_LOG_FATAL("file_handle::io_state::operator() called with invalid index");
            std::terminate();
          }
          this->result.value()[idx].second = bytes_transferred;
        }
      }
      this->parent->service()->_work_done();
      // Are we done?
      if(!--this->items_to_go)
        this->completion(this);
    }
    virtual ~state_type() override final
    {
      // Do we need to cancel pending i/o?
      if(this->items_to_go)
      {
        for(size_t n = 0; n < this->items; n++)
        {
#if BOOST_AFIO_USE_POSIX_AIO
          int ret = aio_cancel(this->parent->native_handle().fd, aiocbs + n);
#if 0
          if(ret<0 || ret==AIO_NOTCANCELED)
          {
            std::cout << "Failed to cancel " << (aiocbs+n) << std::endl;
          }
          else if(ret==AIO_CANCELED)
          {
            std::cout << "Cancelled " << (aiocbs+n) << std::endl;
          }
          else if(ret==AIO_ALLDONE)
          {
            std::cout << "Already done " << (aiocbs+n) << std::endl;
          }
#endif
#else
#error todo
#endif
        }
        // Pump the i/o service until all pending i/o is completed
        while(this->items_to_go)
        {
          auto res = this->parent->service()->run();
#ifndef NDEBUG
          if(res.has_error())
          {
            BOOST_AFIO_LOG_FATAL("file_handle: io_service failed");
            std::terminate();
          }
          if(!res.get())
          {
            BOOST_AFIO_LOG_FATAL("file_handle: io_service returns no work when i/o has not completed");
            std::terminate();
          }
#endif
        }
      }
    }
  } * state;
  extent_type offset = reqs.offset;
  size_t statelen = sizeof(state_type) + (reqs.buffers.size() - 1) * sizeof(struct aiocb), items(reqs.buffers.size());
  using return_type = io_state_ptr<CompletionRoutine, BuffersType>;
#if BOOST_AFIO_USE_POSIX_AIO && defined(AIO_LISTIO_MAX)
  if(items > AIO_LISTIO_MAX)
    return make_errored_result<return_type>(stl11::errc::invalid_argument);
#endif
  void *mem = ::calloc(1, statelen);
  if(!mem)
    return make_errored_result<return_type>(stl11::errc::not_enough_memory);
  return_type _state((_io_state_type<CompletionRoutine, BuffersType> *) mem);
  new((state = (state_type *) mem)) state_type(this, operation, std::forward<CompletionRoutine>(completion), items);
  // Noexcept move the buffers from req into result
  BuffersType &out = state->result.value();
  out = std::move(reqs.buffers);
  for(size_t n = 0; n < items; n++)
  {
#if BOOST_AFIO_USE_POSIX_AIO
    struct aiocb *aiocb = state->aiocbs + n;
    aiocb->aio_fildes = _v.fd;
    aiocb->aio_offset = offset;
    aiocb->aio_buf = (void *) out[n].first;
    aiocb->aio_nbytes = out[n].second;
    aiocb->aio_sigevent.sigev_notify = SIGEV_NONE;
    aiocb->aio_sigevent.sigev_value.sival_ptr = (void *) state;
    aiocb->aio_lio_opcode = (operation == operation_t::write) ? LIO_WRITE : LIO_READ;
#else
#error todo
#endif
    offset += out[n].second;
    ++state->items_to_go;
  }
  int ret = 0;
#if BOOST_AFIO_USE_POSIX_AIO
  if(service()->using_kqueues())
  {
#if BOOST_AFIO_COMPILE_KQUEUES
    // Only issue one kqueue event when entire scatter-gather has completed
    struct _sigev = {0};
#error todo
#endif
  }
  else
  {
    // Add these i/o's to the quick aio_suspend list
    service()->_aiocbsv.resize(service()->_aiocbsv.size() + items);
    struct aiocb **thislist = service()->_aiocbsv.data() + service()->_aiocbsv.size() - items;
    for(size_t n = 0; n < items; n++)
    {
      struct aiocb *aiocb = state->aiocbs + n;
      thislist[n] = aiocb;
    }
    ret = lio_listio(LIO_NOWAIT, thislist, items, nullptr);
  }
#else
#error todo
#endif
  if(ret < 0)
  {
    service()->_aiocbsv.resize(service()->_aiocbsv.size() - items);
    state->items_to_go = 0;
    state->result = make_errored_result<BuffersType>(errno);
    state->completion(state);
    return make_result<return_type>(std::move(_state));
  }
  service()->_work_enqueued(items);
  return make_result<return_type>(std::move(_state));
}

template <class CompletionRoutine> result<file_handle::io_state_ptr<CompletionRoutine, file_handle::buffers_type>> file_handle::async_read(file_handle::io_request<file_handle::buffers_type> reqs, CompletionRoutine &&completion) noexcept
{
  return _begin_io(operation_t::read, std::move(reqs), [completion = std::forward<CompletionRoutine>(completion)](auto *state) { completion(state->parent, state->result); }, nullptr);
}

template <class CompletionRoutine> result<file_handle::io_state_ptr<CompletionRoutine, file_handle::const_buffers_type>> file_handle::async_write(file_handle::io_request<file_handle::const_buffers_type> reqs, CompletionRoutine &&completion) noexcept
{
  return _begin_io(operation_t::write, std::move(reqs), [completion = std::forward<CompletionRoutine>(completion)](auto *state) { completion(state->parent, state->result); }, nullptr);
}

file_handle::io_result<file_handle::buffers_type> file_handle::read(file_handle::io_request<file_handle::buffers_type> reqs, deadline d) noexcept
{
  io_result<buffers_type> ret;
  auto _io_state(_begin_io(operation_t::read, std::move(reqs), [&ret](auto *state) { ret = std::move(state->result); }, nullptr));
  BOOST_OUTCOME_FILTER_ERROR(io_state, _io_state);

  // While i/o is not done pump i/o completion
  while(!ret.is_ready())
  {
    auto t(_service->run_until(d));
    // If i/o service pump failed or timed out, cancel outstanding i/o and return
    if(!t)
      return make_errored_result<buffers_type>(t.get_error());
#ifndef NDEBUG
    if(!ret.is_ready() && t && !t.get())
    {
      BOOST_AFIO_LOG_FATAL("file_handle: io_service returns no work when i/o has not completed");
      std::terminate();
    }
#endif
  }
  return ret;
}

file_handle::io_result<file_handle::const_buffers_type> file_handle::write(file_handle::io_request<file_handle::const_buffers_type> reqs, deadline d) noexcept
{
  io_result<const_buffers_type> ret;
  auto _io_state(_begin_io(operation_t::write, std::move(reqs), [&ret](auto *state) { ret = std::move(state->result); }, nullptr));
  BOOST_OUTCOME_FILTER_ERROR(io_state, _io_state);

  // While i/o is not done pump i/o completion
  while(!ret.is_ready())
  {
    auto t(_service->run_until(d));
    // If i/o service pump failed or timed out, cancel outstanding i/o and return
    if(!t)
      return make_errored_result<const_buffers_type>(t.get_error());
#ifndef NDEBUG
    if(!ret.is_ready() && t && !t.get())
    {
      BOOST_AFIO_LOG_FATAL("file_handle: io_service returns no work when i/o has not completed");
      std::terminate();
    }
#endif
  }
  return ret;
}

result<file_handle::extent_type> file_handle::truncate(file_handle::extent_type newsize) noexcept
{
  if(ftruncate(_v.fd, newsize) < 0)
    return make_errored_result<extent_type>(errno);
  if(are_safety_fsyncs_issued())
  {
    fsync(_v.fd);
  }
  return newsize;
}

BOOST_AFIO_V2_NAMESPACE_END
