//! \file afio/afio.hpp The master *latest version* AFIO include file. All AFIO consuming libraries should include this header only.
#include "version.hpp"

#if defined(_MSC_VER) && !defined(__clang__)
#define BOOST_AFIO_HEADERS_PATH2 BOOST_AFIO_VERSION_GLUE(v, BOOST_AFIO_HEADERS_VERSION, /afio.hpp)
#else
#define BOOST_AFIO_HEADERS_PATH2 BOOST_AFIO_VERSION_GLUE(v, BOOST_AFIO_HEADERS_VERSION,)/afio.hpp
#endif

#define BOOST_AFIO_HEADERS_PATH4(a) #a
#define BOOST_AFIO_HEADERS_PATH3(a) BOOST_AFIO_HEADERS_PATH4(a)
//! \brief The AFIO headers path generated by the preprocessor from the version
#define BOOST_AFIO_HEADERS_PATH BOOST_AFIO_HEADERS_PATH3(BOOST_AFIO_HEADERS_PATH2)
#include BOOST_AFIO_HEADERS_PATH
#undef BOOST_AFIO_HEADERS_PATH
#undef BOOST_AFIO_HEADERS_PATH2
#undef BOOST_AFIO_HEADERS_PATH3
#undef BOOST_AFIO_HEADERS_PATH4
