# DO NOT EDIT, GENERATED BY SCRIPT
set(afio_TESTS
  "test/test_kernel_decl.hpp"
  "test/tests/directory_handle_create_close/kernel_directory_handle.cpp.hpp"
  "test/tests/directory_handle_enumerate/kernel_directory_handle_enumerate.cpp.hpp"
  "test/tests/file_handle_create_close/kernel_async_file_handle.cpp.hpp"
  "test/tests/file_handle_create_close/kernel_file_handle.cpp.hpp"
  "test/tests/map_handle_create_close/kernel_map_handle.cpp.hpp"
  "test/tests/section_handle_create_close/kernel_section_handle.cpp.hpp"
  "test/tests/directory_handle_create_close/runner.cpp"
  "test/tests/directory_handle_enumerate/runner.cpp"
  "test/tests/file_handle_create_close/runner.cpp"
  "test/tests/file_handle_lock_unlock.cpp"
  "test/tests/map_handle_create_close/runner.cpp"
  "test/tests/section_handle_create_close/runner.cpp"
  "test/tests/shared_fs_mutex.cpp"
)
# DO NOT EDIT, GENERATED BY SCRIPT
set(afio_COMPILE_TESTS
)
# DO NOT EDIT, GENERATED BY SCRIPT
set(afio_COMPILE_FAIL_TESTS
)
