set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armhf)
set(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc-8)
set(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++-8)
set(CMAKE_CXX_FLAGS_INIT "-Wno-attributes -Wno-psabi")
