name: Create release if everything passes

on:
  push:
    branches:
    - develop
  pull_request:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  publish-binaries:
    name: "Publish Binaries"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@v1.8"
        with:
          ignoreActions: "Publish Binaries"
          checkInterval: 60
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Sleep until all binaries get uploaded
        shell: bash
        run: |
         sleep 60

      - name: Download Linux artifacts
        uses: dawidd6/action-download-artifact@v6
        if: steps.waitforstatuschecks.outputs.status == 'success'
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: unittests_linux.yml
          path: artifacts
    
      - name: Download Mac OS artifacts
        uses: dawidd6/action-download-artifact@v6
        if: steps.waitforstatuschecks.outputs.status == 'success'
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: unittests_macos.yml
          path: artifacts
    
      - name: Download Windows artifacts
        uses: dawidd6/action-download-artifact@v6
        if: steps.waitforstatuschecks.outputs.status == 'success'
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: unittests_windows.yml
          path: artifacts
    
#      - name: Delete Tag
#        uses: dev-drprasad/delete-tag-and-release@v0.1.2
#        with:
#          delete_release: true
#          tag_name: last_all_tests_passing
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename artifacts
        if: steps.waitforstatuschecks.outputs.status == 'success'
        shell: bash
        run: |
         mv "artifacts/Linux error_code g++ prebuilt binaries/llfio-v2.0-binaries-linux-x64.tgz" llfio-v2.0-binaries-ubuntu22.04-x64-error_code.tgz
         mv "artifacts/Linux status_code g++ prebuilt binaries/llfio-v2.0-binaries-linux-x64.tgz" llfio-v2.0-binaries-ubuntu22.04-x64-status_code.tgz
         mv "artifacts/Linux error_code arm-linux-gnueabihf-g++ prebuilt binaries/llfio-v2.0-binaries-linux-armhf.tgz" llfio-v2.0-binaries-ubuntu22.04-armhf-error_code.tgz
         mv "artifacts/Linux status_code arm-linux-gnueabihf-g++ prebuilt binaries/llfio-v2.0-binaries-linux-armhf.tgz" llfio-v2.0-binaries-ubuntu22.04-armhf-status_code.tgz
         mv "artifacts/Mac OS error_code prebuilt binaries/llfio-v2.0-binaries-darwin-arm64.tgz" llfio-v2.0-binaries-macos-arm64-error_code.tgz
         mv "artifacts/Mac OS status_code prebuilt binaries/llfio-v2.0-binaries-darwin-arm64.tgz" llfio-v2.0-binaries-macos-arm64-status_code.tgz
         mv "artifacts/Windows VS2022 error_code prebuilt binaries/llfio-v2.0-binaries-win64.zip" llfio-v2.0-binaries-win64-vs2022-error_code.zip
         mv "artifacts/Windows VS2022 status_code prebuilt binaries/llfio-v2.0-binaries-win64.zip" llfio-v2.0-binaries-win64-vs2022-status_code.zip

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: steps.waitforstatuschecks.outputs.status == 'success'
        with:
          tag_name: all_tests_passed_${{ github.sha }}
          name: All tests passed ${{ github.sha }}
          body: |
            ```
            ${{ github.event.head_commit.message }}
            ```
            
            Prebuilt binaries with development headers and documentation for common platforms are in Assets below:
          draft: false
          prerelease: true
          files: llfio-v2.0-binaries-*
