name: Unit tests Windows

on:
  push:
    branches:
    - develop
    - master
  pull_request:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  WinVS2022:
    name: Visual Studio
    strategy:
      fail-fast: false
      matrix:
        image: [windows-2022]
        configuration: [error_code, status_code]
    runs-on: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v3

    - name: Set name
      id: vars
      shell: bash
      run: |
       if [ "${{ matrix.image }}" = "windows-2025" ]; then
         NAME=VS2025;
         GENERATOR="Visual Studio 18 2025";
       else
         NAME=VS2022;
         GENERATOR="Visual Studio 17 2022";
       fi
       echo ::set-output name=NAME::${NAME}
       echo ::set-output name=GENERATOR::${GENERATOR}

          
    - name: CMake tests Windows
      shell: bash
      env:
        NAME: ${{ steps.vars.outputs.NAME }}-${{ matrix.configuration }}
      run: |
       if [ "${{ matrix.configuration }}" = "status_code" ]; then
         export CMAKE_CONFIGURE_OPTIONS="-DLLFIO_USE_EXPERIMENTAL_SG14_STATUS_CODE=ON"
       fi
       ctest -S .ci.cmake -VV --timeout 900 "-DCTEST_CONFIGURE_OPTIONS=$CMAKE_CONFIGURE_OPTIONS" -DCTEST_SITE=$NAME -DCTEST_CMAKE_GENERATOR="${{ steps.vars.outputs.GENERATOR }}"
      
    - name: Upload Prebuilt Binaries
      uses: actions/upload-artifact@v3
      with:
        name: Windows ${{ steps.vars.outputs.NAME }} ${{ matrix.configuration }} prebuilt binaries
        path: llfio-v2.0-binaries-win64.zip
      
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Windows ${{ steps.vars.outputs.NAME }} ${{ matrix.configuration }} test results
        path: prebuilt/merged_junit_results.xml

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: [WinVS2022]
    runs-on: ubuntu-latest
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: Unit Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: '**/merged_junit_results.xml'
